### ISSUE TITLE
Refactor render.h/.c

### ISSUE THREAD

**Issue by mattp0** [dgpalmieri/aurora#16]
- [x] Copy render.h to render.hpp
- [x] Copy render.c to render.cpp
- [ ] Write tests for render.hpp
- [ ] Write test for render.cpp
- [ ] Convert to C++17
- [ ] Write tests for any new functionality created during the C -> C++ conversion

**Comment by cinderbdt** [comment]
I need to instantiate a Noise object in render.cpp, so I need to use the code in #24 that is waiting to be merged.
