### ISSUE TITLE
Add an 'all' option to the makefile

### ISSUE THREAD

**Issue by dgpalmieri** [dgpalmieri/aurora#3]

**Comment by cinderbdt** [comment]
I'm not 100% sure what is wanted here, but I think I'll set up an all recipe in the root that creates a "release" folder and calls the recipes in the Code subdirectory to make the sp2ppm file, then copies it to release, and does the same for epr. I'm not sure about the Library.  Any input from the rest of the team on what this issue means would be helpful.

**Comment by dgpalmieri** [comment]
This was an issue that I made during the first few days of seeing the code - IIRC, the idea was that there should be an option that sets up everything that you need to run the program (basically combining all commands from the readme). Considering it now, maybe this needs to be a small bash 'install' script instead, since the logic for doing things like checking if `sp2ppm` is already in your .local/bin and if that dir is on your path exceeds (imo) what I would expect from a Makefile.

**Comment by dgpalmieri** [comment]
Archive
